MaLacoste Footwear/Models/Sneaker.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MaLacoste_Footwear.Models
{
    public class Sneaker
    {
        // EF will instruct the database to automatically generate this value, since it is the primary key and it is the first on the list
        public int SneakerId { get; set; }

        [Required(ErrorMessage ="Please enter a sneaker code.")]
        public string Code { get; set; }

        [Required(ErrorMessage ="Please enter a sneaker name.")]
        public string Name { get; set; }

        [Required(ErrorMessage ="Please enter a sneaker price.")]
        [Column(TypeName ="decimal(18,2)")]
        public decimal Price { get; set; }

        public decimal DiscountPercent => .50M; // A discount of 50% is hard-coded for all products
        public decimal DiscountAmount => Price * DiscountPercent;
        public decimal DiscountPrice => Price - DiscountAmount;
    
        //Slung
        public string Slug
        {
            get
            {
                if (Name == null)
                {
                    return "";
                }
                else
                {
                    return Name.Replace(' ', '-');
                }
            }
        }

        [Required(ErrorMessage ="Please select a brand")]
        public int BrandId { get; set; } //foreign key property
        
        //Navigation properties
        public Brand Brand { get; set; }
    }
}

MaLacoste Footwear/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;

namespace MaLacoste_Footwear.Controllers
{
    public class CartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MaLacoste Footwear/Controllers/ReviewController.cs
using MaLacoste_Footwear.Data;
using MaLacoste_Footwear.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MaLacoste_Footwear.Controllers
{
    public class ReviewController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public ReviewController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Genders = await _appDbContext.Genders.ToListAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Review review)
        {
            if (ModelState.IsValid)
            {
                _appDbContext.Add(review);
                await _appDbContext.SaveChangesAsync();
                return RedirectToAction("Confirmation");
            }
            ViewBag.Genders = await _appDbContext.Genders.ToListAsync();
            return View(review);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var reviews = await _appDbContext.Reviews.Include(r => r.Gender).ToListAsync();
            return View(reviews);
        }

        public IActionResult Confirmation() { return View(); }
    }
}

MaLacoste Footwear/Controllers/SneakerController.cs
using MaLacoste_Footwear.Data;
using MaLacoste_Footwear.Data.DataAccess;
using MaLacoste_Footwear.Models;
using MaLacoste_Footwear.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Linq.Expressions;

namespace MaLacoste_Footwear.Controllers
{
    public class SneakerController : Controller
    {
        private readonly IRepositoryWrapper _repo;
        public SneakerController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }
        public int iPageSize = 3;
        public IActionResult List(string id = "all", string sortBy = "name", int productPage = 1) 
        {
            IEnumerable<Sneaker> sneakers; ;
            Expression<Func<Sneaker, object>> orderBy;
            string orderByDirection;
            int iTotalSneakers;

            ViewData["NameSortParam"] = sortBy == "name" ? "name_desc" : "name";
            ViewData["PriceSortParam"] = sortBy == "price" ? "price_desc" : "price";

            if (sortBy.EndsWith("_desc"))
            {
                sortBy = sortBy.Substring(0, sortBy.Length - 5);
                orderByDirection = "desc";
            }
            else
            {
                orderByDirection = "asc";
            }

            string sPropertyName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(sortBy);
            orderBy = p => EF.Property<object>(p, sPropertyName);  //e.g p =>p.Name

            if (id == "all")
            {
                iTotalSneakers = _repo.Sneaker.FindAll().Count();
                sneakers = _repo.Sneaker.GetWithOptions(new QueryOptions<Sneaker>
                {
                    OrderBy = orderBy,
                    OrderByDirection = orderByDirection,
                    PageNumber = productPage,
                    PageSize = iPageSize
                });
            }
            else
            {
                int iBrandId = _repo.Brand.FindByCondition(c => c.BrandName.ToLower() == id)
                    .FirstOrDefault().BrandId;
                iTotalSneakers = _repo.Sneaker.FindByCondition(b => b.BrandId == iBrandId)
                    .Count();
                sneakers = _repo.Sneaker.GetWithOptions(new QueryOptions<Sneaker>
                {
                    OrderBy = orderBy,
                    OrderByDirection = orderByDirection,
                    Where = p => p.BrandId == iBrandId,
                    PageNumber = productPage,
                    PageSize = iPageSize
                });
            }

            var model = new SneakerListViewModel
            {
                Sneakers = sneakers,
                SelectedBrand = id,
                PagingInfo = new PagingInfoViewModel
                {
                    CurrentPage=productPage,
                    ItemsPerPage=iPageSize,
                    TotalItems = iTotalSneakers
                }
            };
            return View(model);
        }

        public IActionResult Details(int id)
        {
            Sneaker sneaker = _repo.Sneaker.GetById(id);
            if (sneaker is not null)
            {
                //use ViewBag to pass data to view
                ViewBag.ImageFileName = sneaker.Code + "_m.png";

                //bind sneaker to view
                return View(sneaker);
            }
            else
            {
                return RedirectToAction("List");
            }
        }
    }
}

MaLacoste Footwear/Views/Sneaker/Details.cshtml
@model Sneaker
@{
    ViewBag.Title = "Sneaker Details";
}

<h1>Sneaker Details</h1>
<div class="row">
    <div class="col-sm-4">
        @if (ViewBag.ImageFileName is not null)
        {
            <img src="~/images/@ViewBag.ImageFileName"
                 alt="@Model.Name Image"
                 class="img-fluid" />
        }
    </div>

    <div class="col-sm-8">
        <h2>@Model.Name</h2>
        <table class="table table-bordered table-striped">
            <tr>
                <td>List Price:</td>
                <td>@Model.Price.ToString("C")</td>
            </tr>
            <tr>
                <td>Discount Percent:</td>
                <td>@Model.DiscountPercent.ToString("P0")</td>
            </tr>
            <tr>
                <td>Your Price:</td>
                <td>
                    @Model.DiscountPrice.ToString("C")
                    (You save @Model.DiscountAmount.ToString("C"))
                </td>
            </tr>
        </table>
        @if (User.Identity.IsAuthenticated && User.IsInRole("Customer")) @* this will only be available to customers not admin *@
        {
            <a asp-controller="Cart" asp-action="Index"
               asp-route-id="@Model.SneakerId"
               asp-route-slug="@Model.Slug" 
               class="btn btn-primary">Add to Cart</a>
        }
        <a asp-action="List"
           class="btn btn-outline-primary">Return to List</a>
    </div>
</div>

<nav>
    <ul>
       @if(User.Identity.IsAuthenticated)
        {
            @if (User.IsInRole("Customer"))
            {
                <li><a asp-controller="Review" asp-action="Create" class="fst-italic">Write a review</a></li>
            }
            else
            {
                <li><a asp-controller="Review" asp-action="Index" class="fst-italic">View reviews</a></li>
            }
        }
    </ul>
</nav>

MaLacoste Footwear/Views/Sneaker/List.cshtml
@model SneakerListViewModel
@{
    ViewBag.Title = "Sneaker List";
}

<h1>Sneaker List</h1>
<div class="row">

    @*Side menu for brands*@
    <div class="col-sm-2">
       
    </div>

    <div class="col-sm-10">
        @*this takes 10 columns/grids*@
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>
                        <a asp-action="List"
                           asp-route-sortBy="@ViewData["NameSortParam"]"
                           asp-route-id="@Model.SelectedBrand"
                           asp-route-productPage="@Model.PagingInfo.CurrentPage">
                            Name
                        </a>
                    </th>
                    <th>
                        <a asp-action="List"
                           asp-route-sortBy="@ViewData["PriceSortParam"]"
                           asp-route-id="@Model.SelectedBrand"
                           asp-route-productPage="@Model.PagingInfo.CurrentPage">
                            Price
                        </a>
                    </th>
                    <th></th>
                    <th></th>
            </thead>


            <tbody>
                @foreach (var sneaker in Model.Sneakers)
                {
                    <tr>
                        <td>@sneaker.Name</td>
                        <td>@sneaker.Price.ToString("C")</td>
                        <td>
                            <a asp-action="Details"
                               asp-route-id="@sneaker.SneakerId"
                               asp-route-slug="@sneaker.Slug">View Details</a>
                        </td>
                        <td>
                            @if (User.Identity.IsAuthenticated && User.IsInRole("Customer")) @* this will only be available to customers not admin *@
                            {
                                <a asp-controller="Cart" asp-action="Index"
                                   asp-route-id="@sneaker.SneakerId"
                                   asp-route-slug="@sneaker.Slug">Add to Cart</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>

        <div page-model="@Model.PagingInfo" page-action="List"
             page-classes-enabled="true"
             page-class="btn" page-class-normal="btn-outline-dark"
             page-class-selected="btn-primary"
             class="btn-group pull-right m-1">
        </div>
    </div>
</div>