MaLacoste Footwear/Controllers/AdminBrandController.cs
using MaLacoste_Footwear.Data;
using MaLacoste_Footwear.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MaLacoste_Footwear.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminBrandController : Controller
    {
        private readonly IRepositoryWrapper _repo;
        public AdminBrandController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }
        public IActionResult List()
        {
            var brands = _repo.Brand.FindAll().OrderBy(b => b.BrandName).ToList();
            return View(brands);
        }

        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Action = "Add";
            return View("AddUpdate", new Brand());
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            ViewBag.Action = "Update";
            var brand = _repo.Brand.GetById(id);
            return View("AddUpdate", brand);
        }
        [HttpPost]
        public IActionResult Update(Brand brand)
        {
            if (ModelState.IsValid)
            {
                if (brand.BrandId is 0)
                {
                    _repo.Brand.Create(brand);
                    TempData["Message"] = $"{brand.BrandName} has been added";
                }
                else
                {
                    _repo.Brand.Update(brand);
                    TempData["Message"] = $"{brand.BrandName} has been updated";
                }
                _repo.Save();
                return RedirectToAction("List");
            }
            else
            {
                ViewBag.Action = "Save";
                return View("AddUpdate");
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Brand brand = _repo.Brand.GetById(id);
            TempData["Message"] = $"{brand.BrandName} has been deleted";
            return View(brand);
        }
        [HttpPost]
        public IActionResult Delete(Brand brand)
        {
            _repo.Brand.Delete(brand);
            _repo.Save();
            return RedirectToAction("List");
        }
    }
}

MaLacoste Footwear/Controllers/AdminHomeController.cs
using MaLacoste_Footwear.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace MaLacoste_Footwear.Controllers
{
    [Authorize(Roles = "Admin")]
    public class AdminHomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MaLacoste Footwear/Controllers/AdminSneakerController.cs
using MaLacoste_Footwear.Data;
using MaLacoste_Footwear.Models;
using MaLacoste_Footwear.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MaLacoste_Footwear.Controllers
{
   [Authorize(Roles = "Admin")]
    public class AdminSneakerController : Controller
    {
        private IEnumerable<Brand> _brands;
        private readonly IRepositoryWrapper _repo;

        public AdminSneakerController(IRepositoryWrapper repo)
        {
            _repo = repo;
            _brands = _repo.Brand.FindAll()
                .OrderBy(b => b.BrandName);
        }
        public IActionResult List(string id = "all")
        {
            IEnumerable<Sneaker> sneakers;
            if (id == "all")
            {
                sneakers = _repo.Sneaker.FindAll()
                     .OrderBy(p => p.Name);
            }
            else
            {
                sneakers =_repo.Sneaker.GetAllSneakersWithBrandDetails()
                    .Where(s => s.Brand.BrandName.ToLower() == id.ToLower())
                    .OrderBy(b => b.Name);
            }

            var model = new SneakerListViewModel
            {
                Sneakers = sneakers,
                SelectedBrand = id
            };

            //bind sneakers to view
            return View(model);
        }

        public IActionResult Add()
        {
            //create new Sneaker object
            Sneaker sneaker = new(); //create sneaker object

            sneaker.Brand = _repo.Brand.GetById(1); // add Brand object - prevents validation problem

            ViewBag.Action = "Add";
            ViewBag.Brands = _brands;

            return View("AddUpdate", sneaker);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Sneaker sneaker = _repo.Sneaker.GetById(id);

            ViewBag.Action = "Update";
            ViewBag.Brands = _brands;

            return View("AddUpdate", sneaker);
        }
        [HttpPost]
        public IActionResult Update(Sneaker sneaker)
        {
            if (ModelState.IsValid)
            {
                if (sneaker.SneakerId == 0) 
                {
                    _repo.Sneaker.Create(sneaker);
                    TempData["Message"] = $"{sneaker.Name} has been added";
                }
                else 
                {
                    _repo.Sneaker.Update(sneaker);
                    TempData["Message"] = $"{sneaker.Name} has been updated";
                }
                _repo.Save();
                return RedirectToAction("List");
            }
            else
            {
                ViewBag.Action = "Save";
                ViewBag.Brands = _brands;
                return View("AddUpdate", sneaker);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Sneaker sneaker = _repo.Sneaker.GetById(id);
            TempData["Message"] = $"{sneaker.Name} has been deleted";
            return View(sneaker);
        }
        [HttpPost]
        public IActionResult Delete(Sneaker sneaker)
        {
            _repo.Sneaker.Delete(sneaker);
            _repo.Save();
            return RedirectToAction("List");
        }
    }
}

MaLacoste Footwear/Views/Shared/_AdminLayout.cshtml
@{
    Layout = "_Layout";
    string controller =
        ViewContext.RouteData.Values["controller"].ToString().ToLower();
    string action =
        ViewContext.RouteData.Values["action"].ToString().ToLower();
}

<div id="AdminHeader">
    <hr />
    <h2>MaLacoste Footwear Admin</h2>
    <hr />
    <div class="mb-3">
        <a class="@(controller == "adminhome" ? "fw-bold" : "")"
           asp-controller="AdminHome" asp-action="Index">Admin Home</a> |
        <a class="@(controller == "adminsneaker" ? "fw-bold" : "")"
           asp-controller="AdminSneaker" asp-action="List">Sneakers</a> |
        <a class="@(controller == "adminbrand" ? "fw-bold" : "")"
           asp-controller="AdminBrand" asp-action="List">Brands</a>
    </div >
</div>

<div>
    @RenderBody()
</div>

MaLacoste Footwear/Views/Shared/_Layout.cshtml
@{
    string controller =
        ViewContext.RouteData.Values["controller"].ToString();
    string action =
        ViewContext.RouteData.Values["action"].ToString();
}
<!DOCTYPE html>
@* Motloung KE, 2019476593, Software Developer, University of the Free State *@
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewBag.Title - MaLacoste Footwear</title>
    <link rel="stylesheet" asp-href-include="/lib/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" asp-href-include="/css/custom.css" />
    <link rel="stylesheet" asp-href-include="/lib/font-awesome/css/all.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-secondary fixed-top">
            <a class="navbar-brand" href="/">MaLacoste Footwear</a>
            <button class="navbar-toggler" type="button"
                    data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <nav class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav me-auto">

                    <a class="nav-link
                        @(controller == "Home" && action == "Index" ? "active fw-bold text-decoration-underline" : "")"
                       asp-controller="Home" asp-action="Index">Home</a>

                    <a class="nav-link
                        @(controller == "Sneaker" ? "active fw-bold text-decoration-underline" : "")"
                       asp-controller="Sneaker" asp-action="List">Sneakers</a>

                    <a class="nav-link
                        @(controller == "Home" && action == "About" ? "active fw-bold text-decoration-underline" : "")"
                       asp-controller="Home" asp-action="About">About</a>
                </div>

                <ul class="navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-link">
                            Hello, @User.Identity.Name
                            <img profile-user="@User.Identity.Name" />
                        </li>
                        @if (string.Equals(User.Identity.Name.ToUpper(), "ADMIN"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#">Users</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" asp-controller="AdminUser"
                                       asp-action="Index1">User Management</a>
                                    <a class="dropdown-item" asp-controller="AdminRole"
                                       asp-action="Index">Role Management</a>
                                </div>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link
                                @(controller.StartsWith("Admin") ? "active" : "")"
                                   asp-controller="AdminHome" asp-action="Index">Admin</a>
                            </li>
                        }
                       
                        <li class="nav-item">
                            <form asp-action="Logout" asp-controller="Account" method="post">

                                <button class="btn btn-link nav-link" type="submit">Log Out</button>

                            </form>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Register" asp-controller="Account">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-action="Login" asp-controller="Account">Log in</a>
                        </li>
                    }
                </ul>
            </nav>
        </nav>
    </header>
    <main class="container bg-light">
        @RenderBody()
    </main>

  

    <footer class="container text-center">
        <hr />
        <p>
            &copy; @DateTime.Now.Year - MaLacoste Footwear
            <br />
            <i class="fst-italic fw-bold">Created by: KE. Motloung (2019476593)</i>

            <a href="mailto:2019476593@ufs4life.ac.za" target="_blank">
                <i class="fa-solid fa-envelope"></i>
            </a>
            <br />

            <i class="fst-italic">
                Let's connect :
                <a href="https://www.linkedin.com/in/koena-motloung-4a83a9258" target="_blank">
                    <!--target blank means the link will start in a new blank page-->
                    <i class="fab fa-linkedin "></i>
                </a>
            </i>
            <br /><br />
            <div class="bg-dark text-light">
                <i class="fa-brands fa-tiktok fa-1x"></i>
                <i class="fa-brands fa-facebook fa-1x"></i>
                <i class="fa-brands fa-twitter fa-1x"></i>
                <i class="fab fa-whatsapp"></i>
            </div>
        </p>
    </footer>
    <script asp-src-include="/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
</body>
</html>