MaLacoste Footwear/Controllers/ReviewController.cs
using MaLacoste_Footwear.Data;
using MaLacoste_Footwear.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MaLacoste_Footwear.Controllers
{
    public class ReviewController : Controller
    {
        private readonly AppDbContext _appDbContext;

        public ReviewController(AppDbContext appDbContext)
        {
            _appDbContext = appDbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            ViewBag.Genders = await _appDbContext.Genders.ToListAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Review review)
        {
            if (ModelState.IsValid)
            {
                _appDbContext.Add(review);
                await _appDbContext.SaveChangesAsync();
                return RedirectToAction("Confirmation");
            }
            ViewBag.Genders = await _appDbContext.Genders.ToListAsync();
            return View(review);
        }

        [Authorize(Roles = "Admin")]
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var reviews = await _appDbContext.Reviews.Include(r => r.Gender).ToListAsync();
            return View(reviews);
        }

        public IActionResult Confirmation() { return View(); }
    }
}

MaLacoste Footwear/Controllers/SneakerController.cs
using MaLacoste_Footwear.Data;
using MaLacoste_Footwear.Data.DataAccess;
using MaLacoste_Footwear.Models;
using MaLacoste_Footwear.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Globalization;
using System.Linq.Expressions;

namespace MaLacoste_Footwear.Controllers
{
    public class SneakerController : Controller
    {
        private readonly IRepositoryWrapper _repo;
        public SneakerController(IRepositoryWrapper repo)
        {
            _repo = repo;
        }
        public int iPageSize = 3;
        public IActionResult List(string id = "all", string sortBy = "name", int productPage = 1) 
        {
            IEnumerable<Sneaker> sneakers; ;
            Expression<Func<Sneaker, object>> orderBy;
            string orderByDirection;
            int iTotalSneakers;

            ViewData["NameSortParam"] = sortBy == "name" ? "name_desc" : "name";
            ViewData["PriceSortParam"] = sortBy == "price" ? "price_desc" : "price";

            if (sortBy.EndsWith("_desc"))
            {
                sortBy = sortBy.Substring(0, sortBy.Length - 5);
                orderByDirection = "desc";
            }
            else
            {
                orderByDirection = "asc";
            }

            string sPropertyName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(sortBy);
            orderBy = p => EF.Property<object>(p, sPropertyName);  //e.g p =>p.Name

            if (id == "all")
            {
                iTotalSneakers = _repo.Sneaker.FindAll().Count();
                sneakers = _repo.Sneaker.GetWithOptions(new QueryOptions<Sneaker>
                {
                    OrderBy = orderBy,
                    OrderByDirection = orderByDirection,
                    PageNumber = productPage,
                    PageSize = iPageSize
                });
            }
            else
            {
                int iBrandId = _repo.Brand.FindByCondition(c => c.BrandName.ToLower() == id)
                    .FirstOrDefault().BrandId;
                iTotalSneakers = _repo.Sneaker.FindByCondition(b => b.BrandId == iBrandId)
                    .Count();
                sneakers = _repo.Sneaker.GetWithOptions(new QueryOptions<Sneaker>
                {
                    OrderBy = orderBy,
                    OrderByDirection = orderByDirection,
                    Where = p => p.BrandId == iBrandId,
                    PageNumber = productPage,
                    PageSize = iPageSize
                });
            }

            var model = new SneakerListViewModel
            {
                Sneakers = sneakers,
                SelectedBrand = id,
                PagingInfo = new PagingInfoViewModel
                {
                    CurrentPage=productPage,
                    ItemsPerPage=iPageSize,
                    TotalItems = iTotalSneakers
                }
            };
            return View(model);
        }

        public IActionResult Details(int id)
        {
            Sneaker sneaker = _repo.Sneaker.GetById(id);
            if (sneaker is not null)
            {
                //use ViewBag to pass data to view
                ViewBag.ImageFileName = sneaker.Code + "_m.png";

                //bind sneaker to view
                return View(sneaker);
            }
            else
            {
                return RedirectToAction("List");
            }
        }
    }
}

MaLacoste Footwear/Views/Review/Confirmation.cshtml
@{
    ViewData["Title"] = "Review submitted successfully";
}

<h2 class="text-center text-bg-dark">
    Review submitted successfully!!!
</h2>

<br />
<hr />
<a asp-action="Details" asp-controller="Sneaker" class="btn btn-outline-primary">Back</a>

MaLacoste Footwear/Views/Review/Create.cshtml
@model Review

@{
    ViewBag.Title = "Submit Review";
}

<h2>Create Review</h2>

<form asp-action="Create" method="post">
    <br />
    <div class="form-group">
        <label asp-for="Name" class="control-label"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label asp-for="Message" class="control-label"></label>
        <textarea asp-for="Message" class="form-control"></textarea>
        <span asp-validation-for="Message" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <label asp-for="GenderId" class="control-label">Gender</label>
        <select asp-for="GenderId" class="form-control" asp-items="@(new SelectList(ViewBag.Genders, "Id", "Name"))"></select>
        <span asp-validation-for="GenderId" class="text-danger"></span>
    </div>
    <br />
    <div class="form-group">
        <input type="submit" value="Submit" class="btn btn-primary" />
    </div>
</form>

<br />
<hr />
<a asp-action="Details" asp-controller="Sneaker" class="btn btn-outline-primary">Back</a>

MaLacoste Footwear/Views/Review/Index.cshtml
@model IEnumerable<Review>

@{
    ViewBag.Title = "Customer Reviews";
}

<h2>Customer Reviews</h2>

@if (Model.Count() is 0)
{
    <p class="text-danger fst-italic">You have no reviews yet</p>
}
else
{
    <table class="table table-bordered table-hoover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.First().Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Message)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.First().Gender.Name)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var review in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => review.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => review.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => review.Message)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => review.Gender.Name)
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p class="text-danger fw-bold">Total reviews : @Model.Count()</p>
}

<br />
<hr />
<a asp-action="Details" asp-controller="Sneaker" class="btn btn-outline-primary">Back</a>