MaLacoste Footwear/Components/BrandMenuViewComponent.cs
using MaLacoste_Footwear.Data;
using MaLacoste_Footwear.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace MaLacoste_Footwear.Components
{
    public class BrandMenuViewComponent : ViewComponent
    {
        private IRepositoryWrapper _repo;
        public BrandMenuViewComponent(IRepositoryWrapper repo)
        {
            _repo = repo;
        }

        public IViewComponentResult Invoke()
        {
            var model = new BrandListViewModel
            {
                Brands = _repo.Brand.FindAll(),
                SelectedBrand = (string)(RouteData?.Values["id"])
            };
            return View(model);
        }
    }
}

MaLacoste Footwear/Controllers/AdminSneakerController.cs
using MaLacoste_Footwear.Data;
using MaLacoste_Footwear.Models;
using MaLacoste_Footwear.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace MaLacoste_Footwear.Controllers
{
   [Authorize(Roles = "Admin")]
    public class AdminSneakerController : Controller
    {
        private IEnumerable<Brand> _brands;
        private readonly IRepositoryWrapper _repo;

        public AdminSneakerController(IRepositoryWrapper repo)
        {
            _repo = repo;
            _brands = _repo.Brand.FindAll()
                .OrderBy(b => b.BrandName);
        }
        public IActionResult List(string id = "all")
        {
            IEnumerable<Sneaker> sneakers;
            if (id == "all")
            {
                sneakers = _repo.Sneaker.FindAll()
                     .OrderBy(p => p.Name);
            }
            else
            {
                sneakers =_repo.Sneaker.GetAllSneakersWithBrandDetails()
                    .Where(s => s.Brand.BrandName.ToLower() == id.ToLower())
                    .OrderBy(b => b.Name);
            }

            var model = new SneakerListViewModel
            {
                Sneakers = sneakers,
                SelectedBrand = id
            };

            //bind sneakers to view
            return View(model);
        }

        public IActionResult Add()
        {
            //create new Sneaker object
            Sneaker sneaker = new(); //create sneaker object

            sneaker.Brand = _repo.Brand.GetById(1); // add Brand object - prevents validation problem

            ViewBag.Action = "Add";
            ViewBag.Brands = _brands;

            return View("AddUpdate", sneaker);
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            Sneaker sneaker = _repo.Sneaker.GetById(id);

            ViewBag.Action = "Update";
            ViewBag.Brands = _brands;

            return View("AddUpdate", sneaker);
        }
        [HttpPost]
        public IActionResult Update(Sneaker sneaker)
        {
            if (ModelState.IsValid)
            {
                if (sneaker.SneakerId == 0) 
                {
                    _repo.Sneaker.Create(sneaker);
                    TempData["Message"] = $"{sneaker.Name} has been added";
                }
                else 
                {
                    _repo.Sneaker.Update(sneaker);
                    TempData["Message"] = $"{sneaker.Name} has been updated";
                }
                _repo.Save();
                return RedirectToAction("List");
            }
            else
            {
                ViewBag.Action = "Save";
                ViewBag.Brands = _brands;
                return View("AddUpdate", sneaker);
            }
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            Sneaker sneaker = _repo.Sneaker.GetById(id);
            TempData["Message"] = $"{sneaker.Name} has been deleted";
            return View(sneaker);
        }
        [HttpPost]
        public IActionResult Delete(Sneaker sneaker)
        {
            _repo.Sneaker.Delete(sneaker);
            _repo.Save();
            return RedirectToAction("List");
        }
    }
}

MaLacoste Footwear/Views/AdminSneaker/AddUpdate.cshtml
<!-- this view is used for the Add action and the Update action -->
@model Sneaker
@{
    Layout = "_AdminLayout";
    string title = ViewBag.Action + " Sneaker";
    ViewBag.Title = title;    // sets title to "Add Sneaker" or "Update Sneaker"
}

<h1>@ViewBag.Title</h1>

<form asp-action="Update" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="BrandId">Brand</label>
        <select asp-for="BrandId"
                asp-items="@(new SelectList(ViewBag.Brands,
                         "BrandId", "BrandName",
                         Model.BrandId.ToString()))"
                class="form-control"></select>
    </div>

    <div class="form-group">
        <label asp-for="Code">Code</label>
        <input asp-for="Code" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Name">Name</label>
        <input asp-for="Name" class="form-control">
    </div>

    <div class="form-group">
        <label asp-for="Price">Price</label>
        <input asp-for="Price" class="form-control">
    </div>

    <input type="hidden" asp-for="SneakerId" />

    <button type="submit" class="btn btn-primary">@ViewBag.Action</button>
    <a asp-action="List" class="btn btn-primary">Cancel</a>
</form>

MaLacoste Footwear/Views/AdminSneaker/Delete.cshtml
@model Sneaker
@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Delete Sneaker";
}

<h1>Confirm Deletion</h1>
<h3>@Model.Name</h3>

<form asp-action="Delete" method="post">
    <input type="hidden" asp-for="SneakerId" />

    <button type="submit" class="btn btn-primary">Delete</button>
    <a asp-action="List" class="btn btn-primary">Cancel</a>
</form>

MaLacoste Footwear/Views/AdminSneaker/List.cshtml
@model SneakerListViewModel
@{
    Layout = "_AdminLayout";
    ViewBag.Title = "Sneaker Manager";
}

<h1>@ViewBag.Title</h1>

@*dismissable alert*@
@if (TempData["Message"] is not null)
{
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        @TempData["Message"]
    </div>
}

<div class="row">
    <div class="col-sm-2">
        <vc:brand-menu></vc:brand-menu> <!--this is with the components, it displays the beautiful menu instead of just a menu -->
    </div>

    <div class="col-sm-10">
        <table class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th class="text-end">Price</th>
                    <th></th>
                    <th></th>
            </thead>
            <tbody>
                @foreach (var p in Model.Sneakers)
                {
                    <tr>
                        <td>@p.Name</td>
                        <td class="text-end">@p.Price.ToString("C")</td>
                        <td>
                            <a asp-action="Update"
                               asp-route-id="@p.SneakerId">Update</a>
                        </td>
                        <td>
                            <a asp-action="Delete"
                               asp-route-id="@p.SneakerId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-action="Add" class="btn btn-primary">Add New Sneaker</a>
    </div>
</div>